pool:
  name: 'AjentPool'

variables:
  version: 'backend_$(Build.BuildId)'

stages:
- stage: CheckoutCode
  displayName: 'Checkout Code'
  jobs:
  - job: checkout
    displayName: 'Checkout Code'
    steps:
    - checkout: self
      clean: true

- stage: BuildDockerImage
  displayName: 'Build Docker Image'
  dependsOn: CheckoutCode
  jobs:
  - job: build
    displayName: 'Build Docker Image'
    steps:
    # Check Docker version and buildx availability
    - script: |
        echo "Checking Docker version"
        which docker
        docker --version
      displayName: 'Check Docker Version'

    # Check if docker buildx is available
    - script: |
        echo "Checking if Buildx is available..."
        if ! docker buildx version > /dev/null 2>&1; then
          echo "Docker Buildx is not installed, installing..."
          mkdir -p ~/.docker/cli-plugins
          curl -sSL https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
          chmod +x ~/.docker/cli-plugins/docker-buildx
          docker buildx version  # Confirm installation
        else
          echo "Docker Buildx is already installed"
          docker buildx version  # Confirm installation
        fi
      displayName: 'Check and Install Docker Buildx'

    # Ensure BuildKit is enabled in the build environment
    - script: |
        echo "Enabling Docker BuildKit..."
        export DOCKER_BUILDKIT=1
        echo "BuildKit: $DOCKER_BUILDKIT"
        docker info | grep "BuildKit" || echo "BuildKit not detected."  # Check if BuildKit is enabled in Docker
        docker buildx ls  # List available builders to confirm buildx setup
      displayName: 'Enable Docker BuildKit and List Builders'

    # Fix permissions for Docker socket (as root)
    - script: |
        echo "Granting permissions to Docker socket..."
        sudo chmod 666 /var/run/docker.sock
      displayName: 'Grant Docker Socket Permissions'

    # Create and use the builder
    - script: |
        echo "Creating and using Docker Buildx builder..."
        docker buildx create --use
        docker buildx ls  # List available builders
      displayName: 'Create and Use Docker Buildx Builder'

    # Build Docker image using buildx
    - script: |
        echo "Building Docker image with buildx..."
        docker buildx build --file Dockerfile --tag perseverance-project:backend_$(Build.BuildId) --build-arg BUILDKIT_INLINE_CACHE=1 --push . || (echo "Docker build failed" && exit 1)
      displayName: 'Build Docker Image with BuildKit'
