pool:
  name: 'AjentPool'

variables:
  version: 'backend_$(Build.BuildId)'

stages:
- stage: CheckoutCode
  displayName: 'Checkout Code'
  jobs:
  - job: checkout
    displayName: 'Checkout Code'
    steps:
    - checkout: self
      clean: true

- stage: BuildDockerImage
  displayName: 'Build Docker Image'
  dependsOn: CheckoutCode
  jobs:
  - job: build
    displayName: 'Build Docker Image'
    steps:
    # Enable BuildKit in the build environment
    - script: |
        export DOCKER_BUILDKIT=1
        docker buildx create --use
        docker buildx ls  # List available builders to confirm
      displayName: 'Enable Docker BuildKit and create buildx builder'

    # Build Docker image using buildx
    - script: |
        docker buildx build --file Dockerfile --tag perseverance-project:backend_$(Build.BuildId) --build-arg BUILDKIT_INLINE_CACHE=1 --push .
      displayName: 'Build Docker Image with BuildKit'

- stage: PushDockerImage
  displayName: 'Push Docker Image'
  dependsOn: BuildDockerImage
  jobs:
  - job: push
    displayName: 'Push Docker Image to ACR'
    steps:
    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        containerRegistry: 'perseverance'
        repository: 'perseverance-project'
        command: 'push'
        tags: |
          $(version)

- stage: CleanupDockerImages
  displayName: 'Clean Up Docker Images'
  dependsOn: PushDockerImage
  jobs:
  - job: cleanup
    displayName: 'Clean Up Docker Images'
    steps:
    - script: |
        images=$(docker images -q)
        if [ -n "$images" ]; then
          docker rmi -f $images
        else
          echo "No images to clean up."
        fi
      displayName: 'Remove all Docker images'

- stage: ModifyAndPublishYaml
  displayName: 'Modify and Publish Kubernetes Manifest'
  dependsOn: CleanupDockerImages
  jobs:
  - job: modifyAndPublish
    displayName: 'Modify Kubernetes Manifest and Publish'
    steps:
    - script: |
        echo "Replacing VERSION with $(version) in backend.yml"
        sed -i '' "s|VERSION|$(version)|g" backend.yml  # For macOS agents, use '-i '''
        cat backend.yml
        cp backend.yml $(Build.ArtifactStagingDirectory)/ 
      displayName: 'Modify Kubernetes Manifest'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Modified Kubernetes Manifest'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'k8s-manifest'
        publishLocation: 'Container'
