pool:
  name: 'AjentPool'

variables:
  version: 'backend_$(Build.BuildId)'

stages:
- stage: CheckoutCode
  displayName: 'Checkout Code'
  jobs:
  - job: checkout
    displayName: 'Checkout Code'
    steps:
    - checkout: self

- stage: BuildDockerImage
  displayName: 'Build Docker Image'
  dependsOn: CheckoutCode
  jobs:
  - job: build
    displayName: 'Build Docker Image'
    steps:
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        containerRegistry: 'perseverance'
        repository: 'perseverance-project'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          backend_$(Build.BuildId)
      name: buildImage

- stage: PushDockerImage
  displayName: 'Push Docker Image'
  dependsOn: BuildDockerImage
  jobs:
  - job: push
    displayName: 'Push Docker Image to ACR'
    steps:
    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        containerRegistry: 'perseverance'
        repository: 'perseverance-project'
        command: 'push'
        tags: |
          $(version)

- stage: CleanupDockerImages
  displayName: 'Clean Up Docker Images'
  dependsOn: PushDockerImage
  jobs:
  - job: cleanup
    displayName: 'Clean Up Docker Images'
    steps:
    - script: |
        # List all running containers and stop them
        running_containers=$(docker ps -q)
        if [ ! -z "$running_containers" ]; then
          echo "Stopping running containers..."
          docker stop $running_containers
          docker rm $running_containers
        else
          echo "No running containers found."
        fi
        
        # List all images and remove them if they exist
        images=$(docker images -aq)
        if [ ! -z "$images" ]; then
          echo "Removing Docker images..."
          docker rmi -f $images || true  # || true to prevent failure if images don't exist
        else
          echo "No Docker images to remove."
        fi
      displayName: 'Stop Containers and Remove Docker Images'

- stage: ModifyAndPublishYaml
  displayName: 'Modify and Publish Kubernetes Manifest'
  dependsOn: CleanupDockerImages
  jobs:
  - job: modifyAndPublish
    displayName: 'Modify Kubernetes Manifest and Publish'
    steps:
    - script: |
        echo "Replacing VERSION with $(version) in backend.yml"
        sed -i "s|VERSION|$(version)|g" backend.yml
        cat backend.yml
        cp backend.yml $(Build.ArtifactStagingDirectory)/ 
      displayName: 'Modify Kubernetes Manifest'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Modified Kubernetes Manifest'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kubernetes-manifest'  # Corrected the typo here
        publishLocation: 'Container'
